name: lightning_node_repository
description: Dart package which manages the lightning node domain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bdk_flutter:
    git:
      url: https://github.com/LtbLightning/bdk-flutter.git
      ref: 9d8b7b96c9ec0c973330c38a17de43d844f8a3e2
  ldk_node:
    git:
      url: https://github.com/LtbLightning/ldk-node-flutter
      ref: main
      
dev_dependencies:
  test: ^1.17.11