class Balance {
  const Balance({
    required this.totalOutboundCapacity,
    required this.confirmed,
    this.untrustedPending = 0,
    this.immature = 0,
    this.trustedPending = 0,
  });

  /// The total of the spendable outbound capacity of all channels
  final int totalOutboundCapacity;

  /// Confirmed and immediately spendable balance
  final int confirmed;

  /// Unconfirmed UTXOs received from an external wallet
  final int untrustedPending;

  /// All coinbase outputs not yet matured
  final int immature;

  /// Unconfirmed UTXOs generated by a wallet tx
  final int trustedPending;

  int get totalSpendable => confirmed + totalOutboundCapacity;
}
