name: mnemonic_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  secure_storage_layer:
    path: ../secure_storage_layer

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
